### ISSUE TITLE
Address a variety of usability fixes, closes #17

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#17] opened 2020-06-03 03:06 UTC
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samanpwbb](https://github.com/samanpwbb)**
_Tuesday Jun 02, 2020 at 08:07 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/23_

----

![Screen Shot 2020-06-02 at 1 05 04 AM](https://user-images.githubusercontent.com/108094/83495881-22c5cb80-a46d-11ea-9c83-629adbc0c16c.png)

This PR does the following things:
- Adds normalize.css to make sure things look similar across browsers
- Reworks the layout and visual styles in the app
- Increases font sizes across the board
- Enables popups to scroll if above a certain size.
- Redesigns the sidebar interaction to no longer use a hamburger button
- Removes the visitor counter (unsure of what the purpose of this was – I can bring it back if it's important)
- Fixes the flyTo animation when selecting a location from the location list
- Ensures all buttons have appropriate sized hit areas

This PR _does not_ do the following things:
- Add labels to the basemap
- Filter markers when filters are selected

Lets address these issues in future PRs since they both require more significant refactors. 

This gif shows off most of the changes on mobile, the primary place where the app will be used:

![2020-06-02 01-00-52 2020-06-02 01_02_05](https://user-images.githubusercontent.com/108094/83495671-dda19980-a46c-11ea-9b6e-e7a840749bd8.gif)

@jdalt for review plz 🙏 

----

_**[samanpwbb](https://github.com/samanpwbb)** included the following code: https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/23/commits_

**Comment by jdalt** [comment] 2020-06-03 03:06
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Tuesday Jun 02, 2020 at 15:15 GMT_

----

Hot take: love it. Unified sidebar solves a lot of the responsive ugliness going on. The counter was desired by the lead organizer and it's like a baby step toward analytics and answering how people are using this. I have more thoughts bubbling on this but not enough time to voice them atm. Hope to fully address by afternoon.

**Comment by jdalt** [comment] 2020-06-03 03:06
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samanpwbb](https://github.com/samanpwbb)**
_Tuesday Jun 02, 2020 at 16:33 GMT_

----

> it's like a baby step toward analytics and answering how people are using this.

I will re-institute the counter but a) you can use your Mapbox account to check usage by map load and referrer – would that be a reasonable alternative to the counter until we have a proper analytics tool set up?

**Comment by jdalt** [comment] 2020-06-03 03:06
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samanpwbb](https://github.com/samanpwbb)**
_Tuesday Jun 02, 2020 at 17:03 GMT_

----

Just resolved conflicts with some other changes, here's the latest. Added the visitor counter back to top right and restyled the new urgent notices:

![Screen Shot 2020-06-02 at 10 01 13 AM](https://user-images.githubusercontent.com/108094/83548199-3c403500-a4b8-11ea-9996-8399520e37fc.png)

@jdalt this should be good to go. Tested on ff/safari/chrome, _not_ IE.

**Comment by samanpwbb** [comment] 2020-06-03 03:08
dupe of https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/1

**Closed by samanpwbb** 2020-06-03 03:08 UTC
