### ISSUE TITLE
Support/site feedback mechanisms? 

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#32] opened 2020-06-03 04:38 UTC
We need to make sure users can surface issues to us without having to go through social channels. 

If we brainstorm some options that work well for us (e.g. integrate with Issues API) we can connect back with the folks in touch with users and make sure it makes sense to them. I'm guessing a comment box would be uncontroversial.

**Comment by omawhite** [comment] 2020-06-03 04:52
Potential duplicate of https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/12

**Comment by omawhite** [comment] 2020-06-03 04:52
Or at least the two are linked

**Comment by mc-funk** [comment] 2020-06-03 05:07
They are related but different since I think we are trying to get site feedback/support into Issues, but Request An Update needs to feed back into data review and updating so it is going to start as a Google form.

**Comment by jdalt** [comment] 2020-06-03 14:51
Somewhat related to https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/36 (or at least how I was interpreting it).

**Comment by experimatt** [comment] 2020-06-03 16:00
I had the same gut reaction as @omawhite - is this a duplicate of #12? But in reading through the rest of the thread and those other issues (#12, #36), I think we're going to quickly have a UX problem of both where to put all these different buttons and feedback mechanisms, and also how to differentiate them. If we're getting confused about them internally, I'm sure end-users will be too.

Having the teams entering data and working on the site being completely separate definitely makes for some communication challenges, both internally and externally.

**Comment by mc-funk** [comment] 2020-06-03 16:18
Hard agree on the confusion. And sorry for my role in causing it with all the issues. 

There are two necessarily distinct things: 
(1) DATA SUBMISSION - this is related to #12 and #23 - the Google Form we will have ready soon needs a link for people to submit info that will be reviewed by our Monitoring team on the organizing side, if the person with the info is not already looped in to our organizational network. Likely not a long term solution for this but it's a distinct and high-priority need. 
(2) SITE SUPPORT/ISSUES/TECHNICAL NEEDS - this is just about how we have a feedback mechanism to our dev team about issues with the site. This is related to #32 (this issue) and #37 

Seems like we need to get those refined into two issues and close some of the excess/repeats

**Comment by mc-funk** [comment] 2020-06-03 18:16
OK, we are going to roll this all into #37 for now until we get clarity on how to better handle this.

**Closed** 2020-06-03 18:17 UTC
Labels: Priority: High, Type: Discussion
