### ISSUE TITLE
[feedback from user] Zooming after clicking on sidebar not working properly

### ISSUE THREAD

**Issue by samanpwbb** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#8] opened 2020-06-03 02:05 UTC
Reported in slack:

![image](https://user-images.githubusercontent.com/108094/83587441-f610c300-a503-11ea-995b-cef7236590fc.png)

Lets see if we can reproduce this behavior.

**Comment by samanpwbb** [comment] 2020-06-03 02:44
These screenshots were also shared:

![image (2)](https://user-images.githubusercontent.com/108094/83589869-58b88d80-a509-11ea-92a0-1052919c711e.png)
![image (1)](https://user-images.githubusercontent.com/108094/83589882-5d7d4180-a509-11ea-987e-b3477a92168c.png)

I think the underlying issue is that the map is hard to read when the user is zoomed out.

**Comment by kmarekspartz** [comment] 2020-06-04 00:00
This could be an underlying mapbox issue, the distinction between page zoom and map zoom.

**Comment by samanpwbb** [comment] 2020-06-04 00:20
I believe this issue is caused by the fact that map touch handlers don't register if user begins a map interaction by touching marker. If the map is covered in markers, markers end up getting in the way of many map interactions. This problem could be fixed by switching to a symbol layer (https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/2).

**Comment by arich** [comment] 2020-06-04 19:54
I couldn't reproduce this on firefox or chrome on a mac, same on a PC on chrome (which looks like what I'm seeing from the user screenshots).

**Comment by amaxama** [comment] 2020-11-12 01:36
Closing this issue as have not experience or heard of it being a problem in the past few months. Feel free to reopen if it continues to be an issue!

**Closed by amaxama** 2020-11-12 01:36 UTC
Labels: Priority: Medium, Type: Bug
